#TamarraJP2
#Programmer: Joshua Tamarra (MJ)
#Email: jtamarra@cnm.edu
#Purpose: Provides user capability to view state info

print("Welcome to state finder\n") #Program title

#Program description
print("This program will tell you the information for a state you input.\n") 

#User input for info about a state
state = input("Please enter the name of a state that you would like to know about: \n")


#List of states & info; By order of when they joined the union


#The list of states
stateList = ['Delaware',
             'Pennsylvania',
             'New Jersey',
             'Georgia',
             'Connecticut',
             'Massachusetts',
             'Maryland',
             'South Carolina',
             'New Hampshire',
             'Virginia',
             'New York',
             'North Carolina',
             'Rhode Island',
             'Vermont',
             'Kentucky',
             'Tennessee',
             'Ohio',
             'Louisiana',
             'Indiana',
             'Mississippi',
             'Illinois',
             'Alabama',
             'Maine',
             'Missouri',
             'Arkansas',
             'Michigan',
             'Florida',
             'Texas',
             'Iowa',
             'Wisconsin',
             'California',
             'Minnesota',
             'Oregon',
             'Kansas',
             'West Virginia', 
             'Nevada',
             'Nebraska',
             'Colorado', 
             'North Dakota', 
             'South Dakota', 
             'Montana',
             'Washington', 
             'Idaho',
             'Wyoming',
             'Utah', 
             'Oklahoma',
             'New Mexico', 
             'Arizona',
             'Alaska',
             'Hawaii',]

#list of capitals
capital = ['Dover',
           'Harrisburg',
           'Trenton',
           'Atlanta',
           'Hartford',
           'Boston',
           'Annapolis',
           'Columbia',
           'Concord',
           'Richmond',
           'Albany',
           'Raleigh', 
           'Providence', 
           'Montpelier', 
           'Frankfort', 
           'Nashville', 
           'Columbus', 
           'Baton Rouge', 
           'Indianapolis', 
           'Jackson', 
           'Springfield', 
           'Montgomery', 
           'Augusta', 
           'Jefferson City', 
           'Little Rock', 
           'Lansing', 
           'Tallahassee', 
           'Austin', 
           'Des Moines', 
           'Madison', 
           'Sacramento', 
           'St. Paul', 
           'Salem', 
           'Topeka', 
           'Charleston', 
           'Carson City', 
           'Lincoln', 
           'Denver', 
           'Bismarck', 
           'Pierre', 
           'Helena', 
           'Olympia', 
           'Boise', 
           'Cheyenne', 
           'Salt Lake City', 
           'Oklahoma City', 
           'Santa Fe', 
           'Pheonix', 
           'Juneau', 
           'Honolulu']

#list of birds
bird = ['Blue Hen Chicken',       
        'Ruffed Grouse',
        'Eastern Goldfinch',
        'Brown Thrasher',
        'American Robin',
        'Chickadee',
        'Baltimore Oriole',
        'Carolina Wren',
        'Purple Finch',
        'Cardinal',
        'bluebird',
        'Cardinal',
        'Rhode Island Red',
        'hermit Thrush',
        'Kentucky Cardinal',
        'Mockingbird',
        'Cardinal', 
        'Pelican', 
        'Cardinal',
        'Mockingbird',
        'Cardinal',
        'Yellowhammer', 
        'Chickadee', 
        'Bluebird', 
        'Mockingbird',
        'Robin',
        'Mockingbird',
        'Mockingbird', 
        'Eastern Goldfinch',
        'Robin', 
        'California Valley Quail',
        'Common Loon', 
        'Western Meadowlark', 
        'Western Meadowlark', 
        'Cardinal', 
        'Mountain Bluebird', 
        'Western Meadowlark', 
        'Lark Bunting', 
        'Western Meadowlark', 
        'Ring-Necked Pheasant',
        'Western Meadowlark', 
        'Willow Goldfinch', 
        'Mountain Bluebird', 
        'Meadowlark', 
        'California Gull', 
        'Scissor-Tailed Flycatcher', 
        'Roadrunner', 
        'Cactus Wren',
        'Willow Ptarmigan',
        'Nene (Hawaiian Goose)']

#order the states joined the union
number = ['1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
          '16',
          '17',
          '18',
          '19',
          '20',
          '21',
          '22',
          '23',
          '24',
          '25',
          '26',
          '27',
          '28',
          '29',
          '30',
          '31',
          '32',
          '33',
          '34',
          '35',
          '36',
          '37',
          '38',
          '39',
          '40',
          '41',
          '42',
          '43',
          '44',
          '45',
          '46',
          '47',
          '48',
          '49',
          '50',]

#output
print("\nThe capital of", state, "is", capital[stateList.index(state)] + ", it's state bird is the", bird[stateList.index(state)] + " and it is state number", number[stateList.index(state)], "in the union.")

#closing
print("\n Thank you for using state info finder! Have a nice day! :)")
